name: very_good_trial

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: flutter packages get

      - name: APK generation
        run: flutter build apk --split-per-abi

      - name: Upload Release APK to Firebase AppDistribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: FlutterTesters
          releaseNotesFile: releaseNotes/releaseNote.txt
          file: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk